# Generated by Django 4.0 on 2021-12-20 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('job_nature', models.CharField(default='Полный рабочий день', max_length=300, verbose_name='График')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                ('premium', models.CharField(choices=[['Нет', 'Нет'], ['Да', 'Да']], default=['Да', 'Да'], max_length=50, verbose_name='Вип')),
                ('info', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Краткое описание')),
                ('experience', models.TextField(default='Опыт работы', verbose_name='Опыт работы')),
                ('features', models.TextField(default='Оссобенности', verbose_name='Особенности работы')),
                ('education', models.CharField(default='Образование', max_length=1000, verbose_name='Образование')),
                ('location', models.CharField(choices=[['п.Караменды', 'п.Караменды'], ['г.Костанай', 'г.Костанай']], default=['п.Караменды', 'п.Караменды'], max_length=50, verbose_name='Город')),
                ('contact', models.CharField(default='Введите контактные данные(почта/телефон/...)', max_length=200, verbose_name='Контактные данные')),
                ('requirements', models.TextField(default='Требуемые качества и навыки', verbose_name='Требования')),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
