# Generated by Django 4.0 on 2021-12-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='slug',
        ),
    ]
