# Generated by Django 4.0 on 2021-12-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_tag_category_jobpost_category_jobpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
