# Generated by Django 4.0 on 2022-01-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_jobpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='contact',
            field=models.CharField(default='', max_length=200, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='education',
            field=models.CharField(default='', max_length=1000, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='experience',
            field=models.TextField(default='', verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='features',
            field=models.TextField(default='', verbose_name='Особенности работы'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_nature',
            field=models.CharField(default='', max_length=300, verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(default='', verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='general.location'),
        ),
    ]
