# Generated by Django 4.0 on 2022-01-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_location_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='features',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='post', to='general.Tag'),
        ),
    ]
