# Generated by Django 4.0 on 2022-02-04 06:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_remove_jobpost_experience_remove_jobpost_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='info',
            field=models.CharField(max_length=110, validators=[django.core.validators.MinLengthValidator(25)], verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 12, 54, 34, 928798)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='tags',
            field=models.ManyToManyField(blank=True, default='--', null=True, related_name='post', to='general.Tag'),
        ),
    ]
