# Generated by Django 4.0 on 2022-02-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_alter_jobpost_info_alter_jobpost_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='post', to='general.Tag'),
        ),
    ]
